- name: setup master
  hosts: buildbot-master
  sudo: yes

  roles:
  - role: hicknhack-software.buildbot/master/nine/create
    buildbot_master_www_port: 8083

  - hicknhack-software.buildbot/master/inplace-config

  - role: hicknhack-software.buildbot/project/add
    project_name: 'Twofold-Qt'
    project_repo_url: 'https://github.com/hicknhack-software/Twofold-Qt.git'
    project_reconfig_master: false
  tags:
  - buildmaster

- name: setup slaves
  hosts: buildbot-slaves
  sudo: yes

  roles:
  - hicknhack-software.buildbot/slave/create
  - example-setups/qt532
  - example-setups/gcc490
  - example-setups/qt532_gcc490
  tags:
  - buildslave

- name: setup winslaves
  hosts: winbot-slaves
  roles:
  - hicknhack-software.buildbot/winslave/create
  - example-setups/qt54_mingw_491
  tags:
  - buildwinslave

- name: start master
  hosts: buildbot-master
  roles:
    - hicknhack-software.buildbot/master/nine/start
  tags:
  - buildmaster

- name: start slaves
  hosts: buildbot-slaves
  roles:
    - hicknhack-software.buildbot/slave/start
  tags:
  - buildslave

- name: start winslaves
  hosts: winbot-slaves
  roles:
  - hicknhack-software.buildbot/winslave/start
  tags:
  - buildwinslave
