- name: setup master
  hosts: buildbot-master
  sudo: yes
  roles:
  - hicknhack-software.buildbot/master/install-nine
  - hicknhack-software.buildbot/master/create
  - hicknhack-software.buildbot/master/inplace-config
  - hicknhack-software.buildbot/project/add
  tags:
  - buildmaster

- name: setup slaves
  hosts: buildbot-slaves
  sudo: yes
  roles:
  - hicknhack-software.buildbot/slave/create
  - example-setups/qt532
  - example-setups/gcc490
  - example-setups/qt532_gcc490
  tags:
  - buildslave

- name: setup winslaves
  hosts: buildbot-winslaves
  roles:
  - hicknhack-software.buildbot/winslave/create
  - example-setups/qt54_mingw491
  tags:
  - buildwinslave

- name: start master
  hosts: buildbot-master
  gather_facts: no
  sudo: yes
  roles:
  - hicknhack-software.buildbot/master/start-inplace
  tags:
  - buildmaster

- name: start slaves
  hosts: buildbot-slaves
  gather_facts: no
  sudo: yes
  roles:
  - hicknhack-software.buildbot/slave/start
  tags:
  - buildslave

- name: start winslaves
  hosts: buildbot-winslaves
  gather_facts: no
  roles:
  - hicknhack-software.buildbot/winslave/start
  tags:
  - buildwinslave
