---
#Tries to install no package, but installs choco

#TODO: choco exists?
- name: Make sure Choco is installed
  win_chocolatey:
    name: "python2"
    ignore_errors: yes
    async: 40

- name: Disable Script Confirmation
  raw: 'choco feature enable -n allowGlobalConfirmation'

- name: Install Required Tools
  win_chocolatey:
    name: "{{ item }}"
    register: packages_result
    failed_when: "('install not successful' in packages_result.stdout)"    
  with_items: required_tools

- name: Create Temporary Directory
  raw: 'mkdir C:/Temp'

- name: Download Qt Module Sources
  raw: 'wget --directory-prefix={{ qt.tmpFolder }} {{ qt.mirrorUrl }}/{{ item.value.archive }}'
  args:
    chdir: "{{ qt.tmpFolder }}"
    creates: "{{ qt.tmpFolder }}/{{ item.value.archive }}"
  with_dict: qt.modules

- name: Extract Qt Sources
  raw: "7z x {{ qt.tmpFolder }}/{{ item.value.archive }}.7z"
  args:
    chdir: "{{ qt.tmpFolder }}"
    creates: "{{ qt.tmpFolder }}/{{ item.value.archive }}"
  with_dict: qt.modules  

- name: Qt | Configure Base
  raw: >
    ./configure -opensource -confirm-license -prefix {{ qt.prefix }}
    -no-libjpeg -no-gif -no-libpng -no-harfbuzz
    -no-widgets -no-compile-examples -no-qml-debug
    -nomake examples -nomake tools -nomake tests
  args:
    chdir: "{{ qt.tmpFolder }}/{{ qt.modules.base.archive }}"
    creates: "{{ qt.tmpFolder }}/{{ qt.modules.base.archive }}/Makefile"