---
#required choco tools
- name: Make sure Choco is installed
  win_chocolatey:
    name: "python2"
    ignore_errors: yes
    async: 20

- name: Disable Script Confirmation
  raw: 'choco feature enable -n allowGlobalConfirmation'

- name: Install Required Tools
  win_chocolatey:
    name: "{{ item }}"
    register: packages_result
    failed_when: no
  with_items: required_tools
  failed_when: no

#Create Target Directory
- name: Stat qt directory
  win_stat:
    path: '{{ qt.prefix }}'
  register: qt54_temporary_dir_result

- name: Create Temporary Directory
  raw: 'mkdir {{ qt.prefix }}'
  when: not qt54_temporary_dir_result.stat.exists

- name: Stat mingw directory
  win_stat:
    path: '{{ mingw.prefix }}'
  register: mingw491_temporary_dir_result

- name: Create Temporary Directory
  raw: 'mkdir {{ mingw.prefix }}'
  when: not mingw491_temporary_dir_result.stat.exists

#download and extract mingw
- name: Check if mingw archive already exists
  win_stat:
    path: '{{ mingw.prefix }}/{{ mingw.archive }}.7z'
  register: mingw_archive_stat_result

- name: Check if mingw binaries already exist
  win_stat:
    path: '{{ mingw.prefix }}/mingw32'
  register: mingw_binaries_stat_result  

- name: Download mingw32-491
  win_get_url:
    url: '{{ mingw.url }}/{{ mingw.archive }}.7z'
    dest: '{{ mingw.prefix }}\{{ mingw.archive }}.7z'
  when: not mingw_archive_stat_result.stat.exists

- name: Extract mingw32-491
  raw: "cd {{ mingw.prefix }} && 7za x {{ mingw.prefix }}/{{ mingw.archive }}.7z"
  when: not mingw_binaries_stat_result.stat.exists  

#download and extract qt
- name: Check if qt archive already exists
  win_stat:
    path: '{{ qt.prefix }}/{{ qt.archive }}.7z'
  register: qt54_base_archive_stat_result

- name: Check if qt binaries already exist
  win_stat:
    path: '{{ qt.prefix }}/5.4'
  register: qt54_base_binaries_stat_result

- name: Download Qt base archive
  win_get_url:
    url: '{{ qt.url }}/{{ qt.archive }}.7z'
    dest: '{{ qt.prefix }}\{{ qt.archive }}.7z'
  when: not qt54_base_archive_stat_result.stat.exists

- name: Extract Qt base sources
  raw: "cd {{ qt.prefix }} && 7za x {{ qt.prefix }}/{{ qt.archive }}.7z"
  when: not qt54_base_binaries_stat_result.stat.exists

- name: Create qt.conf
  raw: >
    echo [Paths] > {{ qt.prefix }}/5.4/mingw491_32/bin/qt.conf && 
    echo Prefix=.. >> {{ qt.prefix }}/5.4/mingw491_32/bin/qt.conf

- name: Create prepare script
  raw: >
    echo set PATH={{ qt.prefix }}\5.4\mingw491_32\bin;{{ mingw.prefix }}\mingw32\bin;%PATH%> {{ buildbot_winslave_basedir }}/scripts/qt54_mingw_491.bat &&
    echo set QMAKESPEC=win32-g++>> {{ buildbot_winslave_basedir }}\scripts\qt54_mingw_491.bat
